source ~/.bashrc
source ~/r1/dotfiles/git-completion.bash

# Setting PATH for Python 3.1
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.1/bin:${PATH}"
export PATH
