set nocompatible
set backspace=indent,eol,start
set textwidth=82

set autoindent

set ch=2
set mousehide

if version >= 500
  let c_comment_strings=1

  if !exists("syntax_on")
    syntax on
  endif

  set hlsearch
endif

colorscheme darkblue
set number
set modeline

set tabstop=4
set shiftwidth=4
set expandtab
set statusline=%t\ %y\ format:\ %{&ff};\ [%c,%l]
set guifont=Monaco:h12

hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white

set cursorline
