set nocompatible
set backspace=indent,eol,start
set textwidth=82

set autoindent

set ch=2
set mousehide

set t_Co=256

if version >= 500
  let c_comment_strings=1

  if !exists("syntax_on")
    syntax on
    colorscheme twilight2
  endif

  set hlsearch
endif

set number
set modeline

set tabstop=4
set shiftwidth=4
set expandtab
set guifont=Monaco:h12

filetype on
filetype plugin on
filetype indent on

hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white

set cursorline

function! StartUp()
    if 0 == argc()
        NERDTree
    end
endfunction

autocmd VimEnter * call StartUp()

